### ISSUE TITLE
Implement Wheel Speed Sensors

### ISSUE THREAD

**Issue by Sedkian** [UMSAE-Formula-Electric/SCU#17]
This task includes writing the necessary code for the implementation of the Wheel Speed Sensors into the SCU.

**Comment by brettstevens38** [comment]
The finished implementation would consist of a C file with a function call that returns the wheel speed.

**Comment by moram03** [comment]
Reference #25 for current state of wheel speed sensors.

**Comment by Sedkian** [comment]
I will close this issue as it is not valid any more because wheel speed sensors were implemented when the code migration happened #25.
