### ISSUE TITLE
Implement IMU

### ISSUE THREAD

**Issue by Sedkian** [UMSAE-Formula-Electric/SCU#20]
This task includes writing the necessary code for the implementation of the IMU into the SCU.

See: [IMU Documents](https://drive.google.com/drive/u/0/folders/1NGEESHkwPHms8-7kH_wranBMmjiV9bdh)

**Comment by moram03** [comment]
Currently working on bringing IMU issue functionality to what we had previously in the SensorSquid repository.

**Comment by moram03** [comment]
Wrote code for CAN to queue IMU packets. IMU packet processing was also implemented.

Currently need to test code with IMU attached to devboard (hopefully it doesn't crash).

**Comment by Sedkian** [comment]
Did you do it so that the IMU has its own rtos task?

**Comment by moram03** [comment]
Yes indeed, it runs under **imuProcessPacketTask**.

**Comment by moram03** [comment]
We have data!!!



![Image](https://github.com/UMSAE-Formula-Electric/SCU/assets/102110847/bd106492-3d5d-4c52-b42b-d71d81ad9a81)

**Comment by moram03** [comment]
IMU merged into main branch.
