### ISSUE TITLE
Implement CAN Bus

### ISSUE THREAD

**Issue by Sedkian** [UMSAE-Formula-Electric/SCU#21]
This task includes writing the necessary code for the implementation of the CAN Bus into the SCU.

**Comment by moram03** [comment]
CAN bus initializes properly on the dev board. Actual testing for the CAN bus will be reliant on progress on the IMU open issue #20 as receiving data from the IMU is dependent on the CAN bus functioning.

**Comment by Sedkian** [comment]
Keep in mind that the SCU will also be communicating with the VCU through CAN.

**Comment by moram03** [comment]
CAN Communication established with IMU.

**Comment by moram03** [comment]
CAN Bus merged into main and then updated from main to include IMU functionality.
