### ISSUE TITLE
Migrate Wheel Speed Code

### ISSUE THREAD

**Issue by Sedkian** [UMSAE-Formula-Electric/SCU#25]
This task includes:

- Copying the Wheel speed code from the sensor squid repo to the SCU repo.

Here are some guidelines:

1. Create a new branch on SCU. Name it 'wheelSpeed'.
2. On the sensor squid repo, check what pins are being used. This can be done using CubeMX or by looking through the code.
3. On the SCU check if those pins are free and can be used. If they are being used, then you need to find alternative pins.
4. Migrate the code and match the pins between the older ones on the sensor squid and the new ones on the SCU.
5. Make sure the SCU has NO conflicts between the pins and make sure that the SCU builds with no erros or warnings.

**Comment by moram03** [comment]
Rewrote the wheel speed code. Much of the code was simplified as it either provided functionality not currently possible to implement in current SCU project or obscured the code/the purpose was unclear.

***NOTE: Overflow case was not considered, it is highly likely that it may need to be added for proper functionality***
