### ISSUE TITLE
Turn USART Logging ON/ OFF

### ISSUE THREAD

**Issue by Sedkian** [UMSAE-Formula-Electric/SCU#35]
Create a global volatile variable that will:

- Control Initialization of USART pins
- Control USART Logging, where in each task there will be a check whether to log or no

**Comment by Sedkian** [comment]
I will leave TODO tasks with the label SCU#35 inline with the code in the code parts where want to control Logging.

**Comment by BreannaStratton** [comment]
I added the controlled logging but I need an STM32 to test it.

**Comment by BreannaStratton** [comment]
Added variable logging in the doLogging.h and doLogging.c files. There is now the option to log to neither, either, or both the SD card and the USART. However the SD logging is not implemented it's just in place to be added.
